---
'on':
  pull_request:
  push:
    branches:
      - main

jobs:
  integration:
    name: Integration
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-15
          - macos-14
          - ubuntu-24.04
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Install homebrew
        if: runner.os == 'macOS'
        run: |
          /bin/bash -c \
            "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Install system prerequisites (MacOS)
        if: runner.os == 'macOS'
        run: brew install zsh vim

      - name: Install system prerequisites (Ubuntu)
        if: runner.os == 'Linux'
        run: |
            sudo apt-get update -y
            sudo apt-get install -y zsh vim

      - name: Install python prerequisites
        run: python3 -m pip install --break-system-packages -r requirements.txt

      - name: Remove existing dotfiles
        run: |
          rm -f $HOME/.gitconfig
          rm -f $HOME/.bashrc

      - name: Deploy dotfiles with dotbot
        run: dotbot -c install.conf.yml
