on:
  pull_request:
  push:
    branches:
      - main
      - feat/added-initial-version

jobs:
  integration:
    name: Integration
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-10.15

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Install homebrew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
